Public Class DpCodeTable
    Inherits BaseSql

    Public Sub New()
        tableName = "dpcode"
        columns = New List(Of String)
        columns.Add("InterfaceType")
        columns.Add("COnumber")
        columns.Add("SLA")
        columns.Add("ShipDate")
        columns.Add("Bill-ToCustomer")
        columns.Add("CustomerPONumber")
        columns.Add("Site")
        columns.Add("Job")
        columns.Add("MPCode")
        columns.Add("Project")
        columns.Add("ItemNumber")
        columns.Add("QuantitytoWork")
        columns.Add("Remarks")
        columns.Add("SeqNo")
        columns.Add("SONbr")
        columns.Add("SOLine")
        columns.Add("Sales/Job")
        columns.Add("NetPrice")
        columns.Add("SubItem")
        columns.Add("CustomerItemComment")
        columns.Add("Transactionnumber")
        columns.Add("UserID")
        columns.Add("Timestamp")
        columns.Add("FileName")
        columns.Add("InvoiceGroup")
        columns.Add("Originalbillingsite")
        columns.Add("InvPeriod")
        columns.Add("InvDate")
        columns.Add("WW_DPCM2_CHR07")
        columns.Add("WW_DPCM2_CHR08")
        columns.Add("WW_DPCM2_CHR09")
        columns.Add("WW_DPCM2_CHR10")
        columns.Add("WW_DPCM2_PT_DESC1")
        columns.Add("WW_DPCM2_PT_DESC2")
        columns.Add("WW_DPCM2_DTE02")
        columns.Add("WW_DPCM2_DTE03")
        columns.Add("WW_DPCM2_DTE04")
        columns.Add("WW_DPCM2_DTE05")
        columns.Add("WW_DPCM2_DEC01")
        columns.Add("WW_DPCM2_DEC02")
        columns.Add("WW_DPCM2_DEC03")
        columns.Add("WW_DPCM2_DEC04")
        columns.Add("WW_DPCM2_DEC05")
        columns.Add("WW_DPCM2_LOG01")
        columns.Add("WW_DPCM2_LOG02")
        columns.Add("WW_DPCM2_LOG03")
        columns.Add("WW_DPCM2_LOG04")
        columns.Add("WW_DPCM2_LOG05")
        columns.Add("SO/INVPrice")
        columns.Add("InvoiceNumber")
    End Sub

End Class
